In [ ]:
from google.colab import files 
uploaded=files.upload()
import pandas as pd
import io

Saving ml lab 3 dataset.csv to ml lab 3 dataset (1).csv

In [ ]:
df = pd.read_csv(io.BytesIO(uploaded['ml lab 3 dataset.csv']))
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
df.isnull()

   Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [ ]:
gfg = pd.DataFrame(df)
mean_value=gfg['Salary'].mean()
gfg['Salary'].fillna(value=mean_value, inplace=True)
print('Updated Dataframe:')
print(gfg)

Updated Dataframe:
   Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes
5   France  35.0  58000.000000       Yes
6    Spain   NaN  52000.000000        No
7   France  48.0  79000.000000       Yes
8  Germany  50.0  83000.000000        No
9   France  37.0  67000.000000       Yes

In [ ]:
ex=pd.DataFrame(df)
mean_valu=ex['Age'].mean()
ex['Age'].fillna(value=mean_valu, inplace=True)
print('Updated Dataframe:')
print(ex)

Updated Dataframe:
   Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [ ]:
df = df.replace({'Country': {'Germany': 5, 'Spain': 9, 'France':65}}) 
df

   Country        Age        Salary Purchased
0       65  44.000000  72000.000000        No
1        9  27.000000  48000.000000       Yes
2        5  30.000000  54000.000000        No
3        9  38.000000  61000.000000        No
4        5  40.000000  63777.777778       Yes
5       65  35.000000  58000.000000       Yes
6        9  38.777778  52000.000000        No
7       65  48.000000  79000.000000       Yes
8        5  50.000000  83000.000000        No
9       65  37.000000  67000.000000       Yes

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
 
def calc_vif(X):
 
    # Calculating VIF
    vif = pd.DataFrame()
    vif["variables"] = X.columns
    vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
 
    return(vif)
 
X = df.iloc[:,:-1]
calc_vif(X)

  variables         VIF
0   Country    2.507450
1       Age  204.090597
2    Salary  213.713378